# docker-compose.yml file
version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "127.0.0.1:8080:80"
      # - "127.0.0.1:80:80"
    networks:
      - internal
    volumes:
      - ./webdir:/var/www/html:z
  #composer:
    #image: composer/composer
    #networks:
    #  - internal
    #ports:
    #  - "127.0.0.1:9001:9000"
    #volumes:
      - ./composer:/app:z
    #container_name: composer.test
    #user: 1000:1000
    #command: ["composer", "install"]
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./composer:/composer:z
      - ./webdir:/var/www/html:z
  db:
    image: mariadb
    restart: always
    networks:
      - internal
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./dev/docker_mysql_init/Recepie_Service.sql:/docker-entrypoint-initdb.d/Recepie_Service.sql:z
      - ./dev/docker_mysql_init/custom.sql:/docker-entrypoint-initdb.d/custom.sql:z
  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - internal
    ports:
      - "127.0.0.1:8082:80"
    environment:
      - PMA_HOST=db
  #adminer:
  #  image: adminer
  #  restart: always
  #  networks:
  #    - internal
  #  ports:
  #    - "127.0.0.1:8081:8080"

networks:
  internal:
    driver: bridge
    
