# docker-compose.yml file
version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "127.0.0.1:8080:80"
      - "127.0.0.1:80:80"
    networks:
      - internal
    volumes:
      - ./webdir:/var/www/html:Z
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./webdir:/var/www/html:Z
  db:
    image: mariadb
    restart: always
    networks:
      - internal
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./dev/docker_mysql_init:/docker-entrypoint-initdb.d/:Z
  adminer:
    image: adminer
    restart: always
    networks:
      - internal
    ports:
      - "127.0.0.1:8081:8080"

networks:
  internal:
    driver: bridge
    
