# docker-compose.yml file
version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "127.0.0.1:8080:80"
      # - "127.0.0.1:80:80"
    networks:
      - internal
    volumes:
      - ./webdir:/var/www/html:Z
  composer:
    image: composer/composer
    networks:
      - internal
    #ports:
    #  - "127.0.0.1:9001:9000"
    volumes:
      - ./composer:/app:Z
    user: "1000:1000"
    container_name: composer.test
    #command: ["chown", "-R", "0:0", "./webdir"]
    command: ["composer", "install"]
    depends_on: 
      php:
        condition: service_healthy
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    #user: 1000:1000
    volumes:
      - ./composer:/composer:Z
      - ./webdir:/var/www/html:Z
    #command: ["chown", "-R", "1000:1000", "./webdir"]
    healthcheck:
      test: ["CMD", "ls"]
      #interval: 10s
      #timeout: 1s
      #retries: 5
  db:
    image: mariadb
    restart: always
    networks:
      - internal
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./dev/docker_mysql_init/Recepie_Service.sql:/docker-entrypoint-initdb.d/Recepie_Service.sql:Z
  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - internal
    ports:
      - "127.0.0.1:8082:80"
    environment:
      - PMA_HOST=db
  #adminer:
  #  image: adminer
  #  restart: always
  #  networks:
  #    - internal
  #  ports:
  #    - "127.0.0.1:8081:8080"

networks:
  internal:
    driver: bridge
    
